stages:
  - deploy

deploy_railway:
  stage: deploy
  image: node:20
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npm install -g @railway/cli
    - railway up --service jumbopizza --ci
