export interface MenuItem {
  id: string;
  name: string;
  description?: string;
  prices: Record<string, number>;
  category: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: string;
  items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: 'signature-pizzas',
    name: 'Signature Pizzas',
    icon: 'pizza',
    items: [
      {
        id: 'garlic-fingers',
        name: 'Garlic Fingers',
        description: 'Classic garlic fingers',
        prices: { S: 14.55, M: 20.95, L: 26.55, XL: 32.55 },
        category: 'signature-pizzas',
      },
      {
        id: 'pepperoni',
        name: 'Pepperoni',
        description: 'Loaded with pepperoni',
        prices: { S: 15.95, M: 21.95, L: 27.95, XL: 33.95 },
        category: 'signature-pizzas',
      },
      {
        id: 'hawaiian',
        name: 'Hawaiian',
        description: 'Ham, pineapples',
        prices: { S: 16.25, M: 22.95, L: 28.75, XL: 34.95 },
        category: 'signature-pizzas',
      },
      {
        id: 'combination',
        name: 'Combination',
        description: 'Pepperoni, mushrooms, green peppers',
        prices: { S: 16.95, M: 23.95, L: 29.95, XL: 35.95 },
        category: 'signature-pizzas',
      },
      {
        id: 'canadian',
        name: 'Canadian',
        description: 'Pepperoni, mushrooms, bacon',
        prices: { S: 16.95, M: 23.95, L: 29.95, XL: 35.95 },
        category: 'signature-pizzas',
      },
      {
        id: 'chicken-fajita',
        name: 'Chicken Fajita Pizza',
        description: 'Chicken, green peppers, red onions',
        prices: { S: 17.00, M: 24.95, L: 32.95, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'all-dressed',
        name: 'All Dressed',
        description: 'Pepperoni, mushrooms, green peppers, green olives',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'vegetarian',
        name: 'Vegetarian',
        description: 'Mushrooms, green peppers, onions, green olives, tomatoes',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'meat-lovers',
        name: 'Meat Lovers',
        description: 'Pepperoni, bacon, ground beef, italian sausage',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'mexican',
        name: 'Mexican',
        description: 'Mushrooms, onions, tomatoes, ground beef, hot peppers',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'mediterranean',
        name: 'Mediterranean',
        description: 'Pesto, tomatoes, onions, black olives, feta, touch of cheese',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'la-margharita',
        name: 'La Margharita',
        description: 'Classic homemade tomato sauce, fresh garlic, fresh basil, fresh oregano, black pepper, black olives, tomatoes',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'jumbo-combo',
        name: 'Jumbo Combo',
        description: 'Pepperoni, mushrooms, green peppers, onions, green olives, bacon',
        prices: { S: 17.75, M: 25.95, L: 32.95, XL: 39.95 },
        category: 'signature-pizzas',
      },
      {
        id: 'meatza',
        name: "Meat'za",
        description: 'Pepperoni, bacon, ground beef, chicken',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'bbq-pizza',
        name: 'BBQ Pizza',
        description: 'BBQ Chicken, ground beef, onions, hot peppers, bacon',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'smoky-bbq',
        name: 'Smoky BBQ',
        description: 'Grilled smoky BBQ chicken, italian sausages, bacon, cherry tomatoes',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 39.75 },
        category: 'signature-pizzas',
      },
      {
        id: 'alfredo-broccoli-chicken',
        name: 'Alfredo-Broccoli Chicken',
        description: 'Grilled chicken in Alfredo sauce, fresh garlic, black pepper, broccoli',
        prices: { S: 17.00, M: 24.95, L: 32.75, XL: 37.75 },
        category: 'signature-pizzas',
      },
    ],
  },
  {
    id: 'gourmet-pizzas',
    name: 'Gourmet Pizzas',
    icon: 'star',
    items: [
      {
        id: 'supreme-pickle',
        name: 'The Supreme Pickle Pizza',
        description: 'House garlic, pickles, mozzarella',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'ny-style',
        name: 'New York Style Pizza',
        description: '1 inch double pepperoni, double cheese',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'ny-deep-fried-curds',
        name: 'New York Deep Fried Cheese Curds Pizza',
        description: 'Double pepperoni + deep fried cheese curds',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'the-perogy',
        name: 'The Perogy',
        description: 'Stuffed crust, perogies, cheddar, bacon, green onions, sour cream',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'chicken-wings-pizza',
        name: 'Chicken Wings Pizza',
        description: 'Stuffed crust, boneless chicken wings, pepperoni, mozzarella',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'donair-pizza',
        name: 'Donair Pizza',
        description: 'Gyro donair slices, red onions, cherry tomatoes, sweet sauce',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'montreal-smoked-meat',
        name: 'Montreal Smoked Meat Pizza',
        description: 'Stuffed with mozzarella or cheddar',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'pogo-bacon-poutine-pizza',
        name: 'Pogo Bacon Poutine Pizza',
        description: 'Stuffed crust, Pogo, Bacon, St-Albert curds, poutine sauce, homemade fries',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'traditional-pizza-poutine',
        name: 'Traditional Pizza Poutine',
        description: 'Stuffed crust, St-Albert curds, poutine sauce, homemade fries',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
      {
        id: 'curly-fries-poutine-pizza',
        name: 'Curly Fries Pizza Poutine',
        description: 'Stuffed crust, curds, poutine sauce, curly fries',
        prices: { S: 19.95, M: 26.95, L: 34.95, XL: 40.95 },
        category: 'gourmet-pizzas',
      },
    ],
  },
  {
    id: 'fries',
    name: 'Fries',
    icon: 'flame',
    items: [
      {
        id: 'traditional-fries',
        name: 'Traditional Fries',
        description: 'Fresh cut russet potatoes',
        prices: { S: 8.50, L: 13.50 },
        category: 'fries',
      },
      {
        id: 'curly-fries',
        name: 'The Curly',
        description: 'Spiral-seasoned curly fries',
        prices: { S: 9.50, L: 14.50 },
        category: 'fries',
      },
      {
        id: 'crinkle-fries',
        name: 'The Crinkle',
        description: 'Crinkle-cut fries',
        prices: { S: 9.50, L: 14.50 },
        category: 'fries',
      },
      {
        id: 'shoestring-fries',
        name: 'The Shoestring',
        description: 'Thin shoestring fries',
        prices: { S: 9.50, L: 14.50 },
        category: 'fries',
      },
    ],
  },
  {
    id: 'poutine',
    name: 'Poutine',
    icon: 'utensils',
    items: [
      {
        id: 'traditional-poutine',
        name: 'Traditional Poutine',
        description: 'Classic poutine with St-Albert curds and poutine sauce',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'popcorn-chicken-poutine',
        name: 'Popcorn Chicken Poutine',
        description: 'Poutine topped with popcorn chicken',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'las-vegas-poutine',
        name: 'Las Vegas Poutine',
        description: 'Onion rings + bacon poutine',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'curly-poutine',
        name: 'Curly Poutine',
        description: 'Gourmet poutine with curly fries',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'crinkle-poutine',
        name: 'Crinkle Poutine',
        description: 'Gourmet poutine with crinkle fries',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'shoestring-poutine',
        name: 'Shoestring Poutine',
        description: 'Gourmet poutine with shoestring fries',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'curly-deep-fried-curds-poutine',
        name: 'Curly Deep Fried Curds Poutine',
        description: 'Curly fries with deep fried cheese curds',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'popcorn-chicken-curds-poutine',
        name: 'Popcorn Chicken & Deep Fried Curds Poutine',
        description: 'Popcorn chicken with deep fried curds',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'bacon-pogo-poutine',
        name: 'Bacon and Pogo Poutine',
        description: 'Bacon and Pogo sausage poutine',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
      {
        id: 'bikers-poutine',
        name: "Biker's Poutine",
        description: 'Grilled onions + bacon poutine',
        prices: { S: 13.95, L: 17.95 },
        category: 'poutine',
      },
    ],
  },
  {
    id: 'appetizers',
    name: 'Appetizers',
    icon: 'sandwich',
    items: [
      {
        id: 'chinese-chicken-balls',
        name: 'Chinese Chicken Balls (10)',
        prices: { Regular: 12.95 },
        category: 'appetizers',
      },
      {
        id: 'egg-roll',
        name: 'Egg Roll (6)',
        prices: { Regular: 12.95 },
        category: 'appetizers',
      },
      {
        id: 'onion-rings',
        name: 'Onion Rings',
        prices: { Regular: 11.95 },
        category: 'appetizers',
      },
      {
        id: 'mozzarella-sticks',
        name: 'Mozzarella Cheese Sticks (10)',
        prices: { Regular: 15.95 },
        category: 'appetizers',
      },
      {
        id: 'zucchini-sticks',
        name: 'Zucchini Sticks (10)',
        prices: { Regular: 13.55 },
        category: 'appetizers',
      },
      {
        id: 'deep-fried-cheese-curds',
        name: 'Deep Fried Cheese Curds',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'cauliflower-bites',
        name: 'Cauliflower Bites (10)',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'mushrooms',
        name: 'Mushrooms (10)',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'broccoli-cheddar-bacon-bites',
        name: 'Broccoli Cheddar Bacon Bites (10)',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'deep-fried-pickles',
        name: 'Deep Fried Pickles (10)',
        prices: { Regular: 14.95 },
        category: 'appetizers',
      },
      {
        id: 'poppers-jalapeno',
        name: 'Poppers / Cream Cheese-Jalapeno (10)',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'mac-cheese-wedges',
        name: 'Macaroni & Cheese Wedges (10)',
        prices: { Regular: 14.95 },
        category: 'appetizers',
      },
      {
        id: 'perogies',
        name: 'Perogies - Potato with 3 Cheese (10)',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'mini-pogos',
        name: 'Mini Pogos (8)',
        prices: { Regular: 14.95 },
        category: 'appetizers',
      },
      {
        id: 'popcorn-chicken',
        name: 'Popcorn Chicken',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
      {
        id: 'chicken-nuggets',
        name: 'Chicken Nuggets',
        prices: { Regular: 13.95 },
        category: 'appetizers',
      },
    ],
  },
  {
    id: 'fried-chicken',
    name: 'Fried Chicken',
    icon: 'drumstick',
    items: [
      {
        id: 'fried-chicken-3pc',
        name: 'Fried Chicken 3 pcs',
        description: 'With fries & gravy',
        prices: { Regular: 18.95 },
        category: 'fried-chicken',
      },
      {
        id: 'fried-chicken-6pc',
        name: 'Fried Chicken 6 pcs',
        description: 'With fries & gravy',
        prices: { Regular: 24.95 },
        category: 'fried-chicken',
      },
      {
        id: 'fried-chicken-9pc',
        name: 'Fried Chicken 9 pcs',
        description: 'With fries & gravy',
        prices: { Regular: 33.95 },
        category: 'fried-chicken',
      },
    ],
  },
  {
    id: 'wings',
    name: 'Wings & Chicken Bites',
    icon: 'flame',
    items: [
      {
        id: 'chicken-wings',
        name: 'Chicken Wings',
        description: 'Choose your sauce: Mild, Medium, Hot, Jamaican Jerk, Frank\'s Hot, Honey Garlic, BBQ, Thai (sweet chili), 3rd Degree Hot',
        prices: { '10': 16.95, '20': 26.95, '30': 35.95 },
        category: 'wings',
      },
      {
        id: 'boneless-wings',
        name: 'Boneless Wings',
        description: 'Choose your sauce: Mild, Medium, Hot, Jamaican Jerk, Frank\'s Hot, Honey Garlic, BBQ, Thai (sweet chili), 3rd Degree Hot',
        prices: { '10': 16.95, '20': 26.95, '30': 35.95 },
        category: 'wings',
      },
      {
        id: 'double-dusted-jumbo-wings',
        name: 'Double Dusted Jumbo Wings',
        description: 'Extra crispy double dusted. Choose your sauce.',
        prices: { '10': 18.95, '20': 28.95, '30': 37.95 },
        category: 'wings',
      },
    ],
  },
  {
    id: 'salads',
    name: 'Salads',
    icon: 'leaf',
    items: [
      {
        id: 'garden-salad',
        name: 'Garden Salad',
        description: 'Lettuce, tomatoes, green peppers, olives, red onions, italian dressing. Add chicken: S +$3 / L +$4',
        prices: { S: 12.95, L: 16.95 },
        category: 'salads',
      },
      {
        id: 'greek-salad',
        name: 'Greek Salad',
        description: 'Lettuce, tomatoes, green peppers, red onions, black olives, feta, greek dressing. Add chicken: S +$3 / L +$4',
        prices: { S: 12.95, L: 16.95 },
        category: 'salads',
      },
      {
        id: 'caesar-salad',
        name: 'Caesar Salad',
        description: 'Romaine lettuce, bacon, croutons, caesar dressing. Add chicken: S +$3 / L +$4',
        prices: { S: 12.95, L: 16.95 },
        category: 'salads',
      },
    ],
  },
  {
    id: 'platters',
    name: 'Platters',
    icon: 'serving-dish',
    items: [
      {
        id: 'summer-platter',
        name: 'Summer Platter',
        prices: { Regular: 33.95 },
        category: 'platters',
      },
      {
        id: 'veggies-platter',
        name: 'Veggies Platter',
        prices: { Regular: 33.95 },
        category: 'platters',
      },
      {
        id: 'popcorn-chicken-platter',
        name: 'Popcorn Chicken Platter',
        prices: { Regular: 19.95 },
        category: 'platters',
      },
      {
        id: 'chicken-nuggets-platter',
        name: 'Chicken Nuggets Platter',
        prices: { Regular: 19.95 },
        category: 'platters',
      },
      {
        id: 'mini-pogo-platter',
        name: 'Mini Pogo Platter',
        prices: { Regular: 19.95 },
        category: 'platters',
      },
      {
        id: 'chicken-fingers-platter',
        name: 'Chicken Fingers Platter',
        prices: { Regular: 19.95 },
        category: 'platters',
      },
    ],
  },
  {
    id: 'pizza-deals',
    name: 'Pizza Deals',
    icon: 'tag',
    items: [
      {
        id: 'pizza-pickles-deal',
        name: 'Pizza & Pickles',
        description: 'Monday–Wednesday special deal',
        prices: { Regular: 33.95 },
        category: 'pizza-deals',
      },
      {
        id: 'pizza-curds-deal',
        name: 'Pizza & Curds',
        description: 'Monday–Wednesday special deal',
        prices: { Regular: 33.95 },
        category: 'pizza-deals',
      },
      {
        id: 'xlarge-deal',
        name: 'X-Large Deal',
        description: 'Monday–Wednesday special deal',
        prices: { Regular: 33.95 },
        category: 'pizza-deals',
      },
      {
        id: 'pizza-wings-deal',
        name: 'Pizza & Wings',
        description: 'Monday–Wednesday special deal',
        prices: { Regular: 33.95 },
        category: 'pizza-deals',
      },
      {
        id: 'medium-deal',
        name: 'Medium Deal',
        description: 'Monday–Wednesday special deal',
        prices: { Regular: 33.95 },
        category: 'pizza-deals',
      },
      {
        id: 'pizza-curly-poutine-deal',
        name: 'Pizza & Curly Poutine',
        description: 'Monday–Wednesday special deal',
        prices: { Regular: 33.95 },
        category: 'pizza-deals',
      },
    ],
  },
  {
    id: 'platter-deals',
    name: 'Platter Deals',
    icon: 'package',
    items: [
      {
        id: 'munchies-platter',
        name: 'Munchies Platter',
        prices: { Regular: 38.95 },
        category: 'platter-deals',
      },
      {
        id: 'game-time-platter',
        name: 'Game Time Platter',
        prices: { Regular: 38.95 },
        category: 'platter-deals',
      },
      {
        id: 'holiday-platter',
        name: 'Holiday Platter',
        prices: { Regular: 38.95 },
        category: 'platter-deals',
      },
      {
        id: 'snack-attack-platter',
        name: 'Snack Attack Platter',
        prices: { Regular: 38.95 },
        category: 'platter-deals',
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    icon: 'candy',
    items: [
      {
        id: 'jumbo-tails-cinnamon',
        name: 'Jumbo Tails Cinnamon',
        prices: { Regular: 5.95 },
        category: 'desserts',
      },
      {
        id: 'jumbo-tails-nutella',
        name: 'Jumbo Tails Nutella',
        prices: { Regular: 6.95 },
        category: 'desserts',
      },
      {
        id: 'kit-kat-dessert-pizza',
        name: 'Kit Kat Dessert Pizza',
        prices: { S: 13.00, M: 16.95, XL: 22.95 },
        category: 'desserts',
      },
      {
        id: 'smarties-dessert-pizza',
        name: 'Smarties Dessert Pizza',
        prices: { S: 13.00, M: 16.95, XL: 22.95 },
        category: 'desserts',
      },
      {
        id: 'cinnamon-dessert-pizza',
        name: 'Cinnamon Dessert Pizza',
        prices: { S: 13.00, M: 16.95, XL: 22.95 },
        category: 'desserts',
      },
      {
        id: 'moose-ears',
        name: 'Moose Ears',
        prices: { Regular: 4.95 },
        category: 'desserts',
      },
    ],
  },
  {
    id: 'beverages',
    name: 'Beverages',
    icon: 'cup',
    items: [
      {
        id: 'soft-drink',
        name: 'Soft Drink',
        prices: { Regular: 2.95 },
        category: 'beverages',
      },
    ],
  },
  {
    id: 'dipping-sauces',
    name: 'Dipping Sauces',
    icon: 'droplet',
    items: [
      {
        id: 'dipping-ranch',
        name: 'Ranch',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-garlic',
        name: 'Garlic',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-marinara',
        name: 'Marinara',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-cheddar-chipotle',
        name: 'Cheddar Chipotle',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-franks',
        name: "Frank's Red Hot",
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-sweet-sauce',
        name: 'Sweet Sauce',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-house-garlic',
        name: 'House Garlic',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
      {
        id: 'dipping-3rd-degree',
        name: '3rd Degree Hot',
        prices: { Regular: 2.95 },
        category: 'dipping-sauces',
      },
    ],
  },
];

export const STUFFED_CRUST_OPTIONS = [
  { name: 'Hot Dog', prices: { S: 3, M: 4, L: 5, XL: 6 } },
  { name: 'Curds', prices: { S: 3, M: 4, L: 5, XL: 6 } },
  { name: 'Cheddar', prices: { S: 3, M: 4, L: 5, XL: 6 } },
  { name: 'Mozzarella', prices: { S: 3, M: 4, L: 5, XL: 6 } },
  { name: 'Bacon', prices: { S: 3, M: 4, L: 5, XL: 6 } },
];

export const CRUST_OPTIONS = [
  'Natural',
  'Cauliflower',
  'Keto',
  'Gluten Free',
];

export const WING_SAUCES = [
  'Mild',
  'Medium',
  'Hot',
  'Jamaican Jerk',
  "Frank's Hot",
  'Honey Garlic',
  'BBQ',
  'Thai (Sweet Chili)',
  '3rd Degree Hot',
];
